[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "genephys_doc"
authors = [{name = "Diego Vidaurre", email = "dvidaurre@gmail.com"}]
dynamic = ["version", "description"]
